from gtts import gTTS
from pydub import AudioSegment
import os

language = 'en'

output_folder = "normal_audio"
os.makedirs(output_folder, exist_ok=True)

words_and_sentences = [
    "hello",
    "sunshine",
    "I can't believe it's already April.",
    "walking quickly",
    "jump",
    "The dog barked loudly.",
    "sky",
    "open the door",
    "She loves painting.",
    "fast",
    "yellow",
    "under the bridge",
    "Music makes me happy.",
    "cold water",
    "laptop",
    "The rain never stopped.",
    "smooth surface",
    "blue",
    "friends forever",
    "He forgot his homework.",
    "tree",
    "bicycle",
    "sandy beach",
    "Life is full of surprises.",
    "cup of tea",
    "green",
    "I met him yesterday.",
    "shiny coin",
    "over the hills",
    "bright stars",
    "Happiness is a journey.",
    "broken clock",
    "coffee",
    "They sang together.",
    "old book",
    "fresh air",
    "She danced beautifully.",
    "running fast",
    "quick brown fox",
    "They built a treehouse.",
    "yellow umbrella",
    "stormy night",
    "I love Saturday mornings.",
    "tiny kitten",
    "red balloon",
    "He solved the puzzle.",
    "morning jog",
    "thunder",
    "silent room",
    "We traveled to Italy.",
    "giant waves",
    "school bus",
    "She always smiles.",
    "warm blanket",
    "mountain peak",
    "He wrote a poem.",
    "funny movie",
    "jumping rope",
    "purple flower",
    "The stars are bright tonight.",
    "golden sunset",
    "empty street",
    "She forgot her keys.",
    "tall building",
    "singing birds",
    "I am feeling great.",
    "peaceful lake",
    "busy market",
    "delicious food",
    "They played soccer.",
    "guitar",
    "dancing shadows",
    "blue jeans",
    "I love reading books.",
    "soft pillow",
    "ancient castle",
    "frozen pond",
    "running shoes",
    "cloudy sky",
    "He is very tall.",
    "picnic basket",
    "wild horse",
    "I miss those days.",
    "tiny village",
    "desert sand",
    "flowing river",
    "They painted the wall.",
    "green meadow",
    "busy city",
    "She laughed out loud.",
    "sparkling water",
    "dark forest",
    "colorful kite",
    "new adventure",
    "I traveled by train.",
    "chilly morning",
    "soft music",
    "He won the race.",
    "empty park",
    "They danced in the rain.",
    "bright morning",
    "purple sky",
    "beautiful song",
    "He lost his wallet.",
    "white clouds",
    "sunny afternoon",
    "old museum",
    "I climbed the mountain.",
    "gold necklace",
    "lonely road",
    "She wrote a letter.",
    "hidden valley",
    "snowy day",
    "cold breeze",
    "warm sunshine",
    "I planted a tree.",
    "silent movie",
    "candle light",
    "They found the treasure.",
    "giant robot",
    "rainy season",
    "jump high",
    "colorful parade",
    "fresh lemonade",
    "He fixed the car.",
    "quiet forest",
    "ocean waves",
    "burning fire",
    "She won the contest.",
    "golden trophy",
    "slippery floor",
    "loud music",
    "The baby is sleeping.",
    "rising sun",
    "spilled milk",
    "They visited the zoo.",
    "crooked path",
    "She drew a picture.",
    "hidden door",
    "silver coins",
    "sharp knife",
    "I took a deep breath.",
    "empty bottle",
    "sticky notes",
    "colorful pens",
    "He found the clue.",
    "stormy weather",
    "muddy shoes",
    "sunny beach",
    "The leaves are falling.",
    "forgotten dreams",
    "cold hands",
    "broken window",
    "They climbed the tower.",
    "endless road",
    "early morning",
    "paper plane",
    "shiny armor",
    "flying dragon",
    "She cooked dinner.",
    "long journey",
    "sweet memory",
    "hot summer",
    "They crossed the river.",
    "floating cloud",
    "rusty key",
    "new beginning",
    "magic show",
    "I heard a whisper.",
    "old painting",
    "silver lining",
    "thick fog",
    "warm hug",
    "She found a kitten.",
    "blue ocean",
    "rolling hills",
    "They opened the gate.",
    "forgotten path",
    "wet pavement",
    "soft blanket",
    "tangled vines",
    "bright moon",
    "I saw a rainbow.",
    "painted wall",
    "lonely bench",
    "hidden treasure",
    "cracked mirror",
    "They built a raft.",
    "cool breeze",
    "wildflowers",
    "tiny insects",
    "falling star",
    "The clock struck midnight.",
    "tall grass",
    "glistening snow",
    "chasing dreams",
    "strong wind",
    "They raced to the finish.",
    "ancient ruins",
    "colorful garden",
    "fast train",
    "brave knight",
    "I tasted freedom.",
    "mysterious forest",
    "golden sands",
    "echoing footsteps",
    "open window",
    "She painted her room.",
    "heavy backpack",
    "lost city",
    "giant pumpkin",
    "wild storm",
    "racing heart",
    "They spotted a deer.",
    "free spirit",
    "twinkling lights",
    "hidden cave",
    "lonely traveler",
    "sweet aroma",
    "melting ice",
    "I saw a shooting star.",
    "colorful fireworks",
    "sleepy town",
    "roaring waterfall",
    "They built a campfire.",
    "crunchy leaves",
    "silent prayer",
    "glowing lantern",
    "open field",
    "The puppy chewed the shoe.",
    "storm clouds",
    "muddy river",
    "broken chair",
    "falling snow",
    "We explored the castle.",
    "cozy fireplace",
    "running water",
    "empty cabin",
    "She watched the sunset.",
    "busy street",
    "mossy rock",
    "creaky stairs",
    "They lost the map.",
    "giant bubble",
    "sweet laughter",
    "wild river",
    "floating boat",
    "She wore a red dress.",
    "sharp pencil",
    "wet grass",
    "rocky cliff",
    "They caught the bus.",
    "cold night",
    "hummingbird",
    "stormy skies",
    "jump rope",
    "sticky candy",
    "He lifted the heavy box.",
    "frozen lake",
    "hidden message",
    "rolling thunder",
    "dusty shelves",
    "empty nest",
    "We planted flowers.",
    "rusty bicycle",
    "cracked sidewalk",
    "long road",
    "early sunrise",
    "colorful sunset",
    "She played the guitar.",
    "heavy rain",
    "falling leaves",
    "They fixed the bridge.",
    "old barn",
    "glittering stars",
    "cool morning",
    "bright colors",
    "smooth rocks",
    "I found a secret garden.",
    "thick book",
    "tiny seeds",
    "They shared a pizza.",
    "glowing stars",
    "red scarf",
    "lonely night",
    "The wind howled outside.",
    "wild adventure",
    "silent tears",
    "bright flashlight",
    "fresh bread",
    "They watched a movie.",
    "broken toy",
    "sunset glow",
    "busy workers",
    "steep hill",
    "fading light",
    "She read a poem.",
    "icy breeze",
    "running deer",
    "sandy dunes",
    "They explored the jungle.",
    "cold rain",
    "warm soup",
    "giant oak",
    "I made a wish.",
    "slippery ice",
    "glowing embers",
    "happy thoughts",
    "floating feather",
    "They wrote a story.",
    "soft sand",
    "colorful beads",
    "tall trees",
    "empty streets",
    "shimmering water",
    "loud thunder",
    "We took a road trip.",
    "burning candles",
    "painted canvas",
    "snowflakes",
    "bright star",
    "She opened the box.",
    "colorful balloons",
    "muddy path",
    "shining sun",
    "They watched the sunrise.",
    "hidden waterfall",
    "smooth glass",
    "flying bird",
    "rusty gate",
    "melting snow",
    "I heard a funny joke.",
    "tiny footsteps",
    "rolling waves",
    "dark alley",
    "swaying trees",
    "They danced under the stars.",
    "busy airport",
    "empty hallway",
    "glowing sunrise",
    "sweet honey",
    "chilly air",
    "silent waves",
    "He sang a song.",
    "falling petals",
    "cold stone",
    "floating island",
    "They baked cookies.",
    "soft wind",
    "wild vines",
    "shimmering sea",
    "forgotten street",
    "warm hands",
    "The ship sailed away.",
    "rusty anchor",
    "empty garden",
    "fresh flowers",
    "bubbling stream",
    "They chased the butterflies.",
    "silent footsteps",
    "bright sunlight",
    "colorful shells",
    "frozen waterfall",
    "rattling windows",
    "She saw a dolphin.",
        "no way",
    "dude what",
    "that's crazy",
    "literally me",
    "ok but like",
    "you have to see this",
    "I swear bro",
    "fr though",
    "dead serious",
    "I'm not even kidding",
    "stop that's so funny",
    "bro chill",
    "wait what happened",
    "nah you're lying",
    "actually insane",
    "I can't even",
    "who even does that",
    "bro that's wild",
    "tell me everything",
    "hold up",
    "not even surprised",
    "no fr?",
    "I don't believe you",
    "what are you saying",
    "he actually said that?",
    "nah I'm dead",
    "bro trust",
    "you're joking",
    "lowkey true",
    "highkey embarrassing",
    "I'm wheezing",
    "nah that's mad",
    "okay but hear me out",
    "it's giving",
    "so real",
    "can't even lie",
    "I miss you dude",
    "this is peak",
    "actual peak fiction",
    "no shot",
    "I'm pulling up",
    "you're cooked",
    "bro you folded",
    "I would simply cry",
    "that's a you problem",
    "bro got caught lacking",
    "skill issue tbh",
    "get good",
    "major L",
    "huge W",
    "dub",
    "nah bro fumbled",
    "bro was not ready",
    "I need context",
    "he's finished",
    "I'm losing it",
    "can't breathe",
    "bro it's 3am",
    "why are we like this",
    "stay mad",
    "be so for real",
    "it's not that deep",
    "touch grass",
    "common L",
    "bro can't even spell",
    "I love you but you're wrong",
    "you need help",
    "someone take his phone",
    "bro logged off",
    "pack it up",
    "do better",
    "instant regret",
    "nah that's crazy work",
    "not my fault",
    "bro said 'trust' and lied",
    "I'm crying real tears",
    "delete your account",
    "you dropped this 👑",
    "bro's fighting for his life",
    "I'm logging off",
    "bro can't keep getting away with this",
    "rate the fit",
    "nah that's fire",
    "drip check",
    "fit goes crazy",
    "I'm literally obsessed",
    "could never be me",
    "it's over",
    "he's cooked",
    "I need a break",
    "bro took it personally",
    "real ones know",
    "never been wrong",
    "based and true",
    "I'm different",
    "built different",
    "day ruined",
    "we're so back",
    "it's wraps",
    "dropped out of the gc",
    "add me back",
    "who invited him",
    "he's tweaking",
    "she's cooking fr",
    "bro's in shambles",
    "you're not beating the allegations",
    "bro's guilty",
    "who asked",
    "ratio",
    "cope",
    "seethe",
    "mald",
    "actual hater",
    "he's cooked bro",
    "ggs",
    "say less",
    "bet",
    "no cap",
    "on god",
    "I'm pulling up rn",
    "need that asap",
    "lock in",
    "you sold",
    "ain't no way",
    "this can't be real",
    "what are we even doing",
    "nah that's different",
    "bro how",
    "impossible",
    "we're cooked",
    "team diff",
    "bro's in 4k",
    "got caught in 8k",
    "not looking good",
    "we ball",
    "keep it pushing",
    "moving different",
    "caught slacking",
    "sleeping on him",
    "woke up blessed",
    "rise and grind",
    "zero riz",
    "negative game",
    "ultimate L",
    "I'm over it",
    "hard carried",
    "carried by the team",
    "carried by vibes",
    "solo queue moment",
    "team gap",
    "pray for me",
    "I'm running on vibes",
    "not enough coffee",
    "bro it's 2am",
    "sleep is optional",
    "we're not surviving this",
    "I got you",
    "say less bro",
    "lock it in",
    "full send",
    "no regrets",
    "we're sending it",
    "absolutely cooked",
    "overcooked",
    "we eat those",
    "easy claps",
    "free win",
    "he's struggling",
    "bro got ratioed irl",
    "clapped",
    "outplayed",
    "diffed",
    "nah he got styled on",
    "he did it for the plot",
    "for the lore",
    "canon event",
    "no fixing that",
    "it's lore now",
    "trust the process",
    "it's part of the arc",
    "down bad",
    "down tremendous",
    "bro fell off",
    "washed",
    "over for bro",
    "she's thriving",
    "living her best life",
    "literally just better",
    "out of pocket",
    "pocket behavior",
    "caught astray",
    "got sniped",
    "who snitched",
    "I'm not mad just disappointed",
    "nah that's nasty",
    "you're wild for that",
    "you've lost it",
    "zero brain cells",
    "negative IQ plays",
    "actual menace",
    "he's unstoppable",
    "driven by chaos",
    "chaos energy",
    "raw unfiltered chaos",
    "the vibes are immaculate",
    "vibe check passed",
    "vibe check failed",
    "this ain't it",
    "caught in 4k lacking",
    "hard to watch",
    "bro's about to fold",
    "folded immediately",
    "speedrun failure",
    "sub 2 minute L",
    "PB in selling",
    "grinded for nothing",
    "nothing to show for it",
    "built different fr",
    "manifesting a win",
    "it's up",
    "we move",
    "this ain't stopping me",
    "weathering the storm",
    "storm passed",
    "lesson learned",
    "gg go next",
    "run it back",
    "best of 3",
    "one more",
    "bro's cooked well done",
    "crispy",
    "overcooked steak moment",
    "unrecoverable",
    "irrecoverable damage",
    "no coming back from that",
    "that's permanent",
    "locked in",
    "I'm him",
    "I'm her",
    "they're them",
    "he's not him",
    "he tried it",
    "good try bro",
    "solid attempt",
    "respect the hustle",
    "grindset mindset",
    "boss moves",
    "CEO energy",
    "can't stop won't stop",
    "final boss energy",
    "small indie dev moment",
    "patch it next update",
    "needs a buff",
    "nerf incoming",
    "balanced as all things should be",
    "mid",
    "mid at best",
    "top tier",
    "S tier",
    "goated",
    "hard carry",
    "actual demon",
    "he's on demon time",
    "I'm on my villain arc",
    "it's giving main character",
    "main character energy",
    "support character moment",
    "npc behavior",
    "side questing",
    "level grinding",
    "final exam arc",
    "test arc",
    "boss fight incoming",
    "skill tree maxed out",
    "we're built for this",
    "we clutch those",
    "absolute clutch",
    "you love to see it",
    "pain",
    "suffering",
    "nothing but pain",
    "embrace the suffering",
    "peak character development",
    "this will build character",
    "training arc moment",
    "montage music playing",
    "insert training montage",
    "they won't see it coming",
    "sneaky beaky like",
    "stealth mission",
    "mission failed we'll get em next time",
    "solid strat",
    "good plan",
    "bad plan",
    "improvised plan",
    "winging it",
    "straight vibes",
    "brain empty",
    "no thoughts",
    "vibes only",
    "mind blank",
    "he blanked out",
    "zoned out",
    "AFK moment",
    "lagging IRL",
    "fps dropped",
    "brain lag",
    "high ping moment",
    "disconnected",
    "reconnecting",
    "connection error",
    "buffering",
    "error 404",
    "brain not found",
    "I need sleep",
    "bro needs milk",
    "drink water",
    "hydrate or diedrate",
    "healthy gamer moment",
    "touch some grass",
    "go outside",
    "nature is healing",
    "sunlight obtained",
    "leveled up",
    "achievement unlocked",
    "quest completed",
    "mission success",
    "victory",
    "easy W",
    "hard fought W",
    "scraped a win",
    "underdog story",
    "comeback story",
    "we're cooking",
    "chefing it up",
    "bro's in the kitchen",
    "chef's kiss",
    "perfect execution",
    "timing impeccable",
    "clutch gene activated",
    "genius play",
    "actual 200 IQ",
    "outsmarted",
    "outplayed completely",
    "mind games",
    "strategy session",
    "we game planned",
    "flawless plan",
    "mission impossible",
    "success rate 1%",
    "pulled it off",
    "unbelievable",
    "legendary",
    "iconic",
    "historic moment",
    "will be remembered",
    "put it in the history books",
    "textbook example",
    "masterclass",
    "perfect form",
    "bro's textbook",
    "studied the blade",
    "never slept",
    "while you were partying",
    "grind never stops",
    "relentless",
    "unstoppable force",
    "immovable object",
    "clash of titans",
    "legendary duel",
    "epic battle",
    "war of attrition",
    "outlasted",
    "survived",
    "thrived",
    "flourished",
    "dominated",
    "overwhelmed",
    "overpowered",
    "outclassed",
    "gap diff",
    "hard diff",
    "washed him",
    "baptized",
    "deleted",
    "erased from existence",
    "banished",
    "sealed away",
    "game over",
    "bro pressed Alt+F4",
    "force quit moment",
    "task manager open",
    "end task",
    "hard reset",
    "factory reset",
]


for i in range(len(words_and_sentences)):
    mp3_path = os.path.join(output_folder, f"normal{i}.mp3")
    myobj = gTTS(text=words_and_sentences[i], lang=language, slow=True)
    myobj.save(mp3_path)

    wav_path = os.path.join(output_folder, f"normal{i}.wav")
    audio = AudioSegment.from_mp3(mp3_path)
    audio.export(wav_path, format="wav")

    os.remove(mp3_path)


    #PLEASE DONT RUN THIS AGAIN, THIS WAS TO MAKE THE DATASET USING TEXT TO SPEECH AND RUNNING IT AGAIN
    #MAY CAUSE ISSUES WITH FILE PATHS OF THE DATASET